"""Dump real numbers from BioSNAP seed-42 interpretability run + case-study
results into a LaTeX macros file the paper can \\input.

Reads:
  outputs/result/.../best_metrics.txt
  outputs/interpretability/biosnap_seed42/biosnap_seed42_interpretability_summary.txt
  outputs/interpretability/biosnap_seed42/figs/plan_A_stats.json
  outputs/interpretability/biosnap_seed42/case_study/aggregate.csv
  outputs/interpretability/biosnap_seed42/case_study/per_row.csv

Writes:
  TAMR-DTI__.../paper_macros.tex
"""

from __future__ import annotations

import ast
import json
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RUN_DIR = ROOT / "outputs/result/stage2-main-06-full-tamr-dti-n8-biosnap-seed42"
INTERP_DIR = ROOT / "outputs/interpretability/biosnap_seed42"
PAPER_DIR = (
    ROOT
    / "TAMR-DTI__Target-Aware_Modulation_and_Mamba-based_Representation_Refinement_for_Drug-Target_Interaction_Prediction"
)
OUT = PAPER_DIR / "paper_macros.tex"


def parse_kv_txt(p: Path) -> dict:
    out = {}
    for line in p.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def main() -> None:
    best = parse_kv_txt(RUN_DIR / "best_metrics.txt")
    interp = parse_kv_txt(INTERP_DIR / "biosnap_seed42_interpretability_summary.txt")
    plan_a = json.loads((INTERP_DIR / "figs/plan_A_stats.json").read_text())
    df_agg = pd.read_csv(INTERP_DIR / "case_study/aggregate.csv")
    df_per = pd.read_csv(INTERP_DIR / "case_study/per_row.csv")

    best_test = ast.literal_eval(best["best_test"])
    best_val = ast.literal_eval(best["best_val"])

    g = plan_a["groups"]

    # Case-study summary numbers
    dhfr = df_agg[df_agg["uniprot"] == "P00374"].iloc[0]
    n_targets = int(len(df_agg))
    n_tp_total = int(df_agg["n_rows"].sum())
    n_sig_targets = int((df_agg["top20_p_combined"] < 0.05).sum())

    # DHFR per-row mean: top-20% k and a; identical across rows since proteins are identical
    dhfr_rows = df_per[df_per["uniprot"] == "P00374"]
    dhfr_a = int(dhfr_rows["top20_a"].iloc[0])
    dhfr_k = int(dhfr_rows["top20_k"].iloc[0])
    dhfr_nb = int(dhfr_rows["n_binding_in_range"].iloc[0])
    dhfr_L = int(dhfr_rows["L_eff"].iloc[0])

    def fmt(x, fmt_str="{:.3f}"):
        try:
            return fmt_str.format(float(x))
        except Exception:
            return str(x)

    lines = [
        "% Auto-generated by scripts/dump_paper_macros.py — DO NOT EDIT BY HAND.",
        "% Source: outputs/result/stage2-main-06-full-tamr-dti-n8-biosnap-seed42 (epoch 46)",
        "",
        "% ---- BioSNAP seed-42 best-checkpoint metrics ----",
        f"\\newcommand{{\\BiosnapValAUROC}}{{{fmt(best_val['auroc'], '{:.4f}')}}}",
        f"\\newcommand{{\\BiosnapValAUPRC}}{{{fmt(best_val['auprc'], '{:.4f}')}}}",
        f"\\newcommand{{\\BiosnapValAcc}}{{{fmt(best_val['accuracy'], '{:.4f}')}}}",
        f"\\newcommand{{\\BiosnapValF1}}{{{fmt(best_val['f1'], '{:.4f}')}}}",
        f"\\newcommand{{\\BiosnapTestAUROC}}{{{fmt(best_test['auroc'], '{:.4f}')}}}",
        f"\\newcommand{{\\BiosnapTestAUPRC}}{{{fmt(best_test['auprc'], '{:.4f}')}}}",
        f"\\newcommand{{\\BiosnapTestAcc}}{{{fmt(best_test['accuracy'], '{:.4f}')}}}",
        f"\\newcommand{{\\BiosnapTestFOne}}{{{fmt(best_test['f1'], '{:.4f}')}}}",
        f"\\newcommand{{\\BiosnapTestAccZeroFive}}{{{fmt(best_test['acc_05'], '{:.4f}')}}}",
        f"\\newcommand{{\\BiosnapTestFOneZeroFive}}{{{fmt(best_test['f1_05'], '{:.4f}')}}}",
        f"\\newcommand{{\\BiosnapValThreshold}}{{{fmt(best_test['threshold'], '{:.2f}')}}}",
        f"\\newcommand{{\\BiosnapBestEpoch}}{{{best['best_epoch']}}}",
        "",
        "% ---- Interpretability summary (n=5493) ----",
        f"\\newcommand{{\\InterpNumSamples}}{{5{','}493}}",
        f"\\newcommand{{\\InterpMambaGate}}{{{fmt(interp['mamba_gate'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpEntropyMean}}{{{fmt(interp['conformer_entropy_norm_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpTopOneMean}}{{{fmt(interp['conformer_top1_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpMarginMean}}{{{fmt(interp['conformer_margin_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpMambaRefineMean}}{{{fmt(interp['mamba_refine_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpMambaRefineMaxMean}}{{{fmt(interp['mamba_refine_max_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpFiLMLOne}}{{{fmt(interp['film_l1_strength_mean'], '{:.4f}')}}}",
        f"\\newcommand{{\\InterpFiLMLTwo}}{{{fmt(interp['film_l2_strength_mean'], '{:.4f}')}}}",
        f"\\newcommand{{\\InterpFiLMLThree}}{{{fmt(interp['film_l3_strength_mean'], '{:.4f}')}}}",
        "",
        "% Per-case-type conformer statistics",
        f"\\newcommand{{\\InterpTPCount}}{{{interp['TP_count']}}}",
        f"\\newcommand{{\\InterpTNCount}}{{{interp['TN_count']}}}",
        f"\\newcommand{{\\InterpFPCount}}{{{interp['FP_count']}}}",
        f"\\newcommand{{\\InterpFNCount}}{{{interp['FN_count']}}}",
        f"\\newcommand{{\\InterpTPTopOne}}{{{fmt(interp['TP_top1_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpTNTopOne}}{{{fmt(interp['TN_top1_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpFPTopOne}}{{{fmt(interp['FP_top1_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpFNTopOne}}{{{fmt(interp['FN_top1_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpTPEntropy}}{{{fmt(interp['TP_entropy_norm_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpTNEntropy}}{{{fmt(interp['TN_entropy_norm_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpFPEntropy}}{{{fmt(interp['FP_entropy_norm_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpFNEntropy}}{{{fmt(interp['FN_entropy_norm_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpTPRefine}}{{{fmt(interp['TP_mamba_refine_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpTNRefine}}{{{fmt(interp['TN_mamba_refine_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpFPRefine}}{{{fmt(interp['FP_mamba_refine_mean'], '{:.3f}')}}}",
        f"\\newcommand{{\\InterpFNRefine}}{{{fmt(interp['FN_mamba_refine_mean'], '{:.3f}')}}}",
        "",
        "% Plan-A rank-medians (sorted-within-sample)",
    ]
    for grp in ("TP", "TN", "FP", "FN"):
        s = g[grp]
        lines += [
            f"\\newcommand{{\\PlanA{grp}RankOne}}{{{fmt(s['rank1_median'], '{:.3f}')}}}",
            f"\\newcommand{{\\PlanA{grp}RankTwo}}{{{fmt(s['rank2_median'], '{:.3f}')}}}",
            f"\\newcommand{{\\PlanA{grp}RankFour}}{{{fmt(s['rank4_median'], '{:.3f}')}}}",
        ]
    lines += [
        "",
        "% ---- Case-study aggregates ----",
        f"\\newcommand{{\\CaseStudyNumTargets}}{{{n_targets}}}",
        f"\\newcommand{{\\CaseStudyNumTPRows}}{{{n_tp_total}}}",
        f"\\newcommand{{\\CaseStudyNumSigTargets}}{{{n_sig_targets}}}",
        f"\\newcommand{{\\CaseStudyDHFRFold}}{{{fmt(dhfr['top20_fold_mean'], '{:.2f}')}}}",
        f"\\newcommand{{\\CaseStudyDHFRPComb}}{{{dhfr['top20_p_combined']:.2e}}}",
        f"\\newcommand{{\\CaseStudyDHFRNRows}}{{{int(dhfr['n_rows'])}}}",
        f"\\newcommand{{\\CaseStudyDHFRNSig}}{{{int(dhfr['top20_n_sig'])}}}",
        f"\\newcommand{{\\CaseStudyDHFRTopK}}{{{dhfr_k}}}",
        f"\\newcommand{{\\CaseStudyDHFRTopA}}{{{dhfr_a}}}",
        f"\\newcommand{{\\CaseStudyDHFRNBinding}}{{{dhfr_nb}}}",
        f"\\newcommand{{\\CaseStudyDHFRLen}}{{{dhfr_L}}}",
        "",
    ]

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[ok] wrote {OUT}  ({len(lines)} lines)")


if __name__ == "__main__":
    main()
